### ISSUE TITLE
'=count-only=' param

### ISSUE THREAD

**Issue by serjrd** [Trakkasure/mikronode#12]
When I execute `/ip address print count-only` in console it returns a proper value.
But when I make an API request through mikronode with `["/ip/address/print", "=count-only="]` as param to `chat.write` it returns an empty array.

API request with just `"/ip/address/print"` returns proper results.

**Comment by gtjoseph** [comment]
I just pushed up a 1.X.X branch.  I tried the =count-only= and it worked fine.

**Comment by Trakkasure** [comment]
This is currently an issue with the es2015 branch. The sentence parser should take care of it with a minor tweak. I'll get to that this afternoon.

**Comment by leo-combes** [comment]
Is it broken again?
I try the same way @serjrd did in his original publication and I get the same empty result with '=count-only=' parameter.
