### ISSUE TITLE
Old version on npm

### ISSUE THREAD

**Issue by bladerunner2020** [Trakkasure/mikronode#15]
npm has 0.3.3 version.
why don't you publish new version there?

**Comment by gtjoseph** [comment]
I've been trying to get Brandon to publish or give me permission to publish for a few months now but no lock.

I'll publish a mikronode-ng this weekend.

**Comment by bladerunner2020** [comment]
thanks

**Comment by gtjoseph** [comment]
Well, I haven't been able to get Brandon to allow me access to publish so I've published mikronode-ng at https://www.npmjs.com/package/mikronode-ng

**Comment by Trakkasure** [comment]
Ok. I'm back I've gotten time to recode much of this into newer node version, and using ES2015 (ex-next) see es2015 branch
I'm up for suggestions to make it better before I merge and publish it.
