### ISSUE TITLE
Node.js 6.1.0+ not working

### ISSUE THREAD

**Issue by lukyer** [Trakkasure/mikronode#19]
Login failure returned from Mikrotik API on Node.js except LTS versions.
Probably because of some connect/hashing node api changes.

Hotfix: use Node.js in LTS version (eg. 4.4.4)

**Comment by gtjoseph** [comment]
I don't know what happened to Trakkasure but I fixed this in my repo.
https://github.com/f5eng/mikronode-ng

**Comment by Trakkasure** [comment]
Sorry guys. I've been slammed in my full time job.

**Comment by Trakkasure** [comment]
Ok. First push of rewrite on es2015 branch.
This also includes using webpack for building, babel for compiling, and my own babel Private property transform plugin.
Let me know what you think.
