### ISSUE TITLE
can't run on node 6.4.x, only node 4.5.

### ISSUE THREAD

**Issue by wantg** [Trakkasure/mikronode#22]

**Comment by Trakkasure** [comment]
Which branch are you working with? The release, yes it is broken. The es2015 branch is working great with engine >4. I'm writing tests for that branch before release. The API has changed a little. There are examples as to how. I will hold off on closing this for your response.

**Comment by wantg** [comment]
I tried mikronode-ng it's worked

**Comment by wantg** [comment]
mikronode(max is 1.0.3)doesn't work on node 6.4.

**Comment by Trakkasure** [comment]
Please checkout and try the es2015 branch from the repo.

**Comment by wantg** [comment]
ok i will try that branch thanks.

**Comment by Trakkasure** [comment]
There's an update coming in about 10-12 hours (after I get off work) that has some bug fixes.

**Comment by Trakkasure** [comment]
FYI: I updated the npm package to use the es2015 branch. 2.0.0-beta.4 is the latest.
Feel free to test with that new code base.
