### ISSUE TITLE
cannot find module mikronode

### ISSUE THREAD

**Issue by facuxt** [Trakkasure/mikronode#23]
Hello.. first let me thank you for all the hard work made in this project. Im trying to use it now and im getting the error in the screenshot attached 
![image](https://cloud.githubusercontent.com/assets/7550822/18769755/59658e84-8106-11e6-9a91-35bb486d461c.png)

I cloned the repository on branch es2015 in the folder node_modules, then i went to that directory and did npm install... then in my script.js i did...
     var api=require('mikronode');

and it doesnt work, im doing something wrong? im using node v6.6.0 

I tried doing npm install mikronode and the same thing occurs

Thanks in advance!

**Comment by Trakkasure** [comment]
Hey, so I replied to this, but don't see the response.
So, I'm replying again.
Please use the NPM version 2.0.0-beta.4 or greater.
This has the sync operation function enabled.

npm install mikronode@2.0.0-beta.4
