### ISSUE TITLE
.connect crashes on attempted connection if api is turned off in radio

### ISSUE THREAD

**Issue by DukeBaird** [Trakkasure/mikronode#3]
If the API is turned off in the mikrotik radio, the attempt to connect causes an error which completely crashes the node process. It won't trap it, and I also cannot catch it.

I know the code that Im using is fine, as if I use it on a radio that the api is turned on in I have no issues at all.

It returns
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)

With the code:
mtik_connection = new mtik(bwtest_ip, mtik_user, mtik_pass, {debug : 5});
mtik_connection.closeOnDone(true);
mtik_connection.connect(function(conn) {})  //<- this line

In theory, the right way to fix this is to use the api to talk to the radio to turn it on, but its the api thats turned off and is refusing all access.

Is there a way to  check if the api is turned on in the radio that wont crash the node process, or return 'could not connect due to api' without dieing?

**Comment by Fibrewire** [comment]
Same problem, the only work around i currently have is to include: 

```javascript
process.on('uncaughtException', function(error) {
    console.error('uncaughtException: ' + error)
});
```

Which doesnt really solve the problem, just avoids the crash

**Comment by andre-luiz-dos-santos** [comment]
@DukeBaird, in your example, you can catch those errors with something like this:

```coffee
mtik_connection.on 'error', (err) ->
    console.dir(err)
```

The output I get with the above is:

```
{ [Error: connect ECONNREFUSED 192.168.7.1:8728]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.7.1',
  port: 8728 }
{}
```

**Comment by Trakkasure** [comment]
Ok. I have been super busy and lazy when not. I will address the issues with this API and provide updates to make this work better.

**Comment by gtjoseph** [comment]
The only mechanism a Socket callback (which is what MikroNode uses internally) has to communicate with the caller is events. If no one is listening for errors and one occurs,  Socket's only option is to throw the fatal uncaught exception.  I've updated the API Docs in the 1.X.X branch to remind the user that they need to listen for error and trap events.
