### ISSUE TITLE
Unable to set or update queue

### ISSUE THREAD

**Issue by edwinallenz** [Trakkasure/mikronode#30]
I'm trying to update a queue `max-limit` but I'm not sure which is the correct format for it, I tried:
1.   ``` chann.write(['/queue/simple/set', `?name=121`, `=max-limit=10k/10k`])```
2.    ``` chann.write(['/queue/simple/set', `name=121`, `=max-limit=10k/10k`])```
3.    ``` chann.write(['/queue/simple/set', `121`, `=max-limit=10k/10k`])```

None of these formats allow me to update the rule properly, any guidance about how to do it will be well received

**Comment by ssbtoday** [comment]
I believe you're using the wrong value for name, it should be numbers instead so the command should look like:
`chann.write(['/queue/simple/set', '=numbers=121', '=max-limit=10k/10k'])`

**Comment by edwinallenz** [comment]
thanks for the update
