### ISSUE TITLE
Not compatible with newer versions of node (^2.0.0-beta.7)

### ISSUE THREAD

**Issue by Fibrewire** [Trakkasure/mikronode#31]
LTS is currently at v6.10.1

var connection = MikroNode.getConnection('93.190.116.3','admin','L1bertyad');

TypeError: MikroNode.getConnection is not a function
    at Object.<anonymous> (C:\Users\AMeusel\Dropbox\GitHub\liberty-tree\tree.js:67:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

**file npm-debug.log**
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'mikronode' ]
2 info using npm@3.10.10
3 info using node@v6.10.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData mikronode@^1.0.3
8 silly fetchNamedPackageData mikronode
9 silly mapToRegistry name mikronode
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'mikronode',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'mikronode',
12 silly mapToRegistry   name: 'mikronode',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/mikronode
14 verbose request uri https://registry.npmjs.org/mikronode
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:38:31 PM
17 verbose request id c70da22766bd6596
18 verbose etag "592834Z25VS5IIKMOMNO8I9Q3"
19 http request GET https://registry.npmjs.org/mikronode
20 http 200 https://registry.npmjs.org/mikronode
21 verbose headers { server: 'nginx/1.10.1',
21 verbose headers   'content-type': 'application/json',
21 verbose headers   'last-modified': 'Thu, 15 Dec 2016 01:40:38 GMT',
21 verbose headers   etag: 'W/"5851f496-755c"',
21 verbose headers   'content-encoding': 'gzip',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   'content-length': '6153',
21 verbose headers   'accept-ranges': 'bytes',
21 verbose headers   date: 'Mon, 03 Apr 2017 14:38:32 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   age: '0',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-lcy1124-LCY',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1491230312.207835,VS0,VE36',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 200,
22 silly get   { server: 'nginx/1.10.1',
22 silly get     'content-type': 'application/json',
22 silly get     'last-modified': 'Thu, 15 Dec 2016 01:40:38 GMT',
22 silly get     etag: 'W/"5851f496-755c"',
22 silly get     'content-encoding': 'gzip',
22 silly get     'cache-control': 'max-age=300',
22 silly get     'content-length': '6153',
22 silly get     'accept-ranges': 'bytes',
22 silly get     date: 'Mon, 03 Apr 2017 14:38:32 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     age: '0',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-lcy1124-LCY',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1491230312.207835,VS0,VE36',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose get saving mikronode to C:\Users\AMeusel\AppData\Roaming\npm-cache\registry.npmjs.org\mikronode\.cache.json
24 verbose correctMkdir C:\Users\AMeusel\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
25 silly fetchPackageMetaData Error: No compatible version found: mikronode@^1.0.3
25 silly fetchPackageMetaData Valid install targets:
25 silly fetchPackageMetaData 2.0.0, 2.0.0-beta.7, 2.0.0-beta.6, 2.0.0-beta.5, 2.0.0-beta.4, 2.0.0-beta.2, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.0
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:178:16)
25 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
25 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\lib\utils\pulse-till-done.js:20:8
25 silly fetchPackageMetaData     at saved (C:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:174:7)
25 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:241:18
25 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:123:15)
25 silly fetchPackageMetaData  error for mikronode@^1.0.3 { Error: No compatible version found: mikronode@^1.0.3
25 silly fetchPackageMetaData Valid install targets:
25 silly fetchPackageMetaData 2.0.0, 2.0.0-beta.7, 2.0.0-beta.6, 2.0.0-beta.5, 2.0.0-beta.4, 2.0.0-beta.2, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.0
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:178:16)
25 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
25 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\lib\utils\pulse-till-done.js:20:8
25 silly fetchPackageMetaData     at saved (C:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:174:7)
25 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:241:18
25 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ETARGET' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: No compatible version found: mikronode@^1.0.3
30 verbose stack Valid install targets:
30 verbose stack 2.0.0, 2.0.0-beta.7, 2.0.0-beta.6, 2.0.0-beta.5, 2.0.0-beta.4, 2.0.0-beta.2, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.0
30 verbose stack
30 verbose stack     at pickVersionFromRegistryDocument (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:178:16)
30 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
30 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\pulse-till-done.js:20:8
30 verbose stack     at saved (C:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:174:7)
30 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:241:18
30 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
31 verbose cwd C:\Users\AMeusel\Dropbox\GitHub\liberty-tree
32 error Windows_NT 10.0.14393
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mikronode"
34 error node v6.10.1
35 error npm  v3.10.10
36 error code ETARGET
37 error notarget No compatible version found: mikronode@^1.0.3
37 error notarget Valid install targets:
37 error notarget 2.0.0, 2.0.0-beta.7, 2.0.0-beta.6, 2.0.0-beta.5, 2.0.0-beta.4, 2.0.0-beta.2, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.0
38 error notarget This is most likely not a problem with npm itself.
38 error notarget In most cases you or one of your dependencies are requesting
38 error notarget a package version that doesn't exist.
39 verbose exit [ 1, true ]

**Comment by Fibrewire** [comment]
use [mikronode-ng](https://www.npmjs.com/package/mikronode-ng) instead

**Comment by Trakkasure** [comment]
Or test es1025 branch.
