### ISSUE TITLE
certificate command issues

### ISSUE THREAD

**Issue by giulianozorzi** [Trakkasure/mikronode#32]
sorry, vrong mikronode :)

**Comment by Trakkasure** [comment]
What was this issue? I am the original Mikronode author.

**Comment by giulianozorzi** [comment]
sorry, i though i was posting on mikronode-ng. I was looking for a way to sign a certificate and could not find a way to pass a nameless parameter like XXX in /certificate sign XXX 

[link here](https://github.com/f5eng/mikronode-ng/issues/18)

g

**Comment by Trakkasure** [comment]
that's fine. Look at my updated implementation. If this works for you, let me know.
It's also "ng"
