### ISSUE TITLE
Listener action close

### ISSUE THREAD

**Issue by williampaulo** [Trakkasure/mikronode#36]
How to listen the action close?
I already tried it but it did not work.

```
  // init

  var device = new MikroNode(host);
  device.connect(login, password).then(function(conn) {
      let chan = conn.openChannel();
      chan.write(['/interface/monitor-traffic', '=interface=<pppoe-pessoa>']);
      chan.data.subscribe(function(data) {
          var packet = MikroNode.resultsToObj(data.data);
          let data_lot = MikroNode.resultsToObj(data.data);
          // test
          chan.close();
      });

      chan.on("close", function() {
          console.log("ok");
      });
  });
```

Is there any method for listening to close action?

**Comment by Trakkasure** [comment]
Channels are not closed automatically. But they do have "done" events.

**Comment by williampaulo** [comment]
ok, thank you!

**Comment by Trakkasure** [comment]
Let me make an adjustment/clarification to that..
channels can me closed automatically if you have "closeOnDone" set to true.
The Done event can notify you of completion of a write command.
Promises returned from a write can let you know that the write has been sent and a response has been returned.
