### ISSUE TITLE
API-ssl support

### ISSUE THREAD

**Issue by apersonnaz** [Trakkasure/mikronode#37]
Hello,

I am trying to connect to a router on the api-ssl service. It works perfectly on the standard api, but I can't get it to work with SSL, and I can't figure out if it is supported or not.
I use version 2.0.1
In the index.js, on the MikroNode constructor comment there is : 
* @param {(object|boolean)} [options.tls] - Set to true to use TLS for this connection.
* Set to an object to use TLS and pass the object to tls.connect as the tls
* options. If your device uses self-signed certificates, you'll either have to
* set 'rejectUnauthorized : false' or supply the proper CA certificate.

But the method itself has only three parameters (IP, port, timeout), and even if I use the setTLS method to set the options, it seems to me that it is never used.

Also I have tried my router with another client on the api-ssl and managed to connect.

Thanks!

**Comment by Trakkasure** [comment]
Right now, I do not have SSL enabled. 
The old version had this feature implemented by another brave soul that tried to clean up the mess I made when first developing this library.
I was working on resolving the other issues I had with the library.
I will now start working on getting SSL implemented.

**Comment by Trakkasure** [comment]
Working on adding this now.

**Comment by Trakkasure** [comment]
Implemented in release 2.3.0. There is an example in the test folder.

**Comment by apersonnaz** [comment]
Great! Thank you so much! I'll try it soon.

**Comment by Trakkasure** [comment]
Keep in mind, 2.3.0 has a breaking change.
It is a simple change, but is required to continue to work. It is the connect and login stages were separated. All examples and tests were updated.

**Comment by leo-combes** [comment]
Is any node minimun version of nodejs required? Now I are testing with node v6.10.3 and get error:

> Error processing sentence: { Error: write EPROTO 139888234383168:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:769:

I have follow your example:

```
    var gateway = new MikroNode(IP, 8729);

    // https://nodejs.org/docs/v6.10.3/api/tls.html#tls_tls_connect_port_host_options_callback
    gateway.TLS({
      rejectUnauthorized : false,
      // If your mikrotik does not have a valid certificate, this cipher is the only one that will work.
      ciphers:'ADH'
    });

    gateway.connect().then(([login])=>login('admin','password')).then(function(conn) {
```
And ADH cipher seems to no exist in node documentation.
There are any error or I am missing something?
