### ISSUE TITLE
Error in doNext unknown parameter

### ISSUE THREAD

**Issue by border-radius** [Trakkasure/mikronode#40]
I have following code:

```javascript
var MikroNode = require('mikronode')
var device = new MikroNode(ipaddress)

device.connect('admin', '').then(connection => {
  console.log('connected')

  var channel = connection.openChannel()
  channel.sync(true)

  console.log('going write 1')

  channel.write('/interface/set', {
    '.id': 'ether2',
    'poe-out': 'forced-on'
  })

  console.log('wrote')

  channel.on('trap', data => {
    console.error(data)
  })

  channel.on('done', data => {
    console.log('done')
    console.log(data)
  })
}).catch(e => {
  throw e
})

```
And when I launching it, it writes:
```
connected
going write 1
wrote
Error in doNext unknown parameter
```
PoE status is not changing. Where I get wrong?
Node version is 7.6.0, mikronode version is 2.1.0

**Comment by Trakkasure** [comment]
Sounds like I have an issue to resolve. Looking into it.

**Comment by Trakkasure** [comment]
As a question, if you use 
```
  channel.write('/interface/set', {
    '.id': 'ether2',
    'poe-out': 'forced-on'
  }).then(data => {
    console.log('done')
    console.log(data)
  });
Does it work?

**Comment by border-radius** [comment]
No, result is the same

**Comment by Trakkasure** [comment]
Ok, so, after double checking, the parameter 'poe-out' seems to be incorrect.
If your device and port do not support this feature, then it would respond with this error.

**Comment by border-radius** [comment]
I got this command which by ssh works with my mikrotik properly: `/interface ethernet poe set ether2 poe-out=forced-on`
However, I already implemented my task with `node-ssh` and everything works fine.

**Comment by Trakkasure** [comment]
Maybe create a support request from Mikrotik. This is an error being reported from the device when tying to set the property.
