### ISSUE TITLE
query word has broken.

### ISSUE THREAD

**Issue by lyonlai** [Trakkasure/mikronode#47]
Yo Man

I'm upgrading my library from version 2.0.1 to the latest 2.3.x. Found an issue with the query word I use with the print command.

```
channel.write('/ip/dhcp-server/lease/print', { address: '10.0.0.25' }
```

should have in the socket level translate the argument object into 

?=address=10.200.0.250

but it's getting me 

`?address=10.200.0.250`

which is not going to work.

**Comment by Trakkasure** [comment]
When creating "print" commands, use array arguments:
```javascript
channel.write('/ip/dhcp-server/lease/print', ["?=address=10.0.0.25"]);
```
This way, the query stack is predictable.
For example:
```javascript
channel.write('/ip/dhcp-server/lease/print', ["?=address=10.0.0.25","?=address=10.0.0.26","?#|","=.proplist=.id,interface,disabled,comment"]);
```
This example returns address that ends in .25 or .26, and only properties: id,interface,disabled,comment
