### ISSUE TITLE
api details

### ISSUE THREAD

**Issue by HERRKIN** [Trakkasure/mikronode#5]
Where Can I find a detailed api documentation? for example in winbox I see /ip/hotspot/users/ but if I have to see the list of users I have to use /ip/hotspot/user/print, I dont know what each resource receives, for example I cant see how I can add an user and asign a profile to it. I went to the api section on the mikrotik wiki but I got just a few things from the examples.

**Comment by Trakkasure** [comment]
Long time reply.. but basically the API mirrors for the most part the command line interface.

**Comment by HERRKIN** [comment]
Some times its hard to tell which arguments the api takes or how they receive it. I had to do it by trial and error. to see what it does.

**Comment by Trakkasure** [comment]
I'll see what I can do to shore up some details. It won't be an easy task. If you want to help I'll put together a wiki to detail them.

**Comment by HERRKIN** [comment]
good, I am not doing mikrotik at the moment but I could help when I get back to the project.
