### ISSUE TITLE
how to use monitor traffic command ?

### ISSUE THREAD

**Issue by xeleniumz** [Trakkasure/mikronode#69]
hi there , I got the problem when i was use command 

`/interface monitor-traffic interface=ether1 once`

when i use this command in mikrotik it response result perfectly because i wants to execute this command only 1 time. here is my code

`   
      
        var api = require('mikronode');
        var device = new api(10.0.0.254'  );
        device.setDebug(api.DEBUG);

        // connect: user, password.
        device.connect().then(([login]) => login('admin', 'admin')).then(function(conn) {
            var c1 = conn.openChannel();
            var c2 = conn.openChannel();
            c1.closeOnDone(true);
            c2.closeOnDone(true);

            console.log('Getting Interfaces');
            c1.write('/interface/monitor-traffic', { 'interface': 'ether1' }); // how to add 'once' to this line ?

            c1.data // get only data here
                .subscribe(function(data) { // feeds in one result line at a time.

                    res.json(data)
                })

        }, function(err) {
            console.log("Error connecting:", err);
        });
`

Best regards

**Comment by Trakkasure** [comment]
changing the write line to be:
```javascript
c1.write('/interface/monitor-traffic', { 'interface': 'ether1', once:true })
```
works to retrieve only one line of the monitor.

**Comment by xeleniumz** [comment]
@Trakkasure thank you for your advance. now it's work !!
