### ISSUE TITLE
example typo/error

### ISSUE THREAD

**Issue by shaunie2fly** [Trakkasure/mikronode#74]
Hey, :)

Thanks for the lib.

Small typo in  the example, left out the 2 :)

        chan2.write('/ip/firewall/print');

        chan2.done.subscribe(function(data){

             // data is all of the sentences in an array.
             data.forEach(function(item) {
                var data = MikroNode.resultsToObj(item.data); // convert array of field items to object.
                console.log('Interface/IP: '+data.interface+"/"+data.address);
             });

        });

    });

**Comment by Trakkasure** [comment]
Thanks for catching that!

**Comment by Trakkasure** [comment]
.. It's fixed.
